# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.6

before_script:
    - python -V # Print out python version for debugging
    - pip install -r backend/requirements.txt # you can also use tox

stages:
    - Static Analysis

flake8:
    stage: Static Analysis
    script:
        - flake8 backend/src/

mypy:
    stage: Static Analysis
    script:
        - mypy backend/src/
