services:
    redis:
        restart: always
    backend:
        image: ${BACKEND_IMAGE_TAG}
        restart: always
        volumes:
            - /backend
            - /midi_files
        environment:
            - ENV=prod
    frontend:
        image: ${FRONTEND_IMAGE_TAG}
        restart: always
        ports:
            - "80:80"
