services:
    backend:
        environment:
            - ENV=dev
        volumes:
            - ./backend:/backend
            - ./midi_files:/midi_files
    frontend:
        environment:
            - PORT=80
        build:
            args:
                NGINX_CONFIG: "./nginx.conf.dev.template"
        ports:
            - "3000:80"
