services:
    backend:
        environment:
            - ENV=dev
            - MONGODB_URL=mongodb://mongodb:27017/soarch-db
        volumes:
            - ./backend:/backend
            - ./midi_files:/midi_files
    frontend:
        environment:
            - PORT=80
        build:
            args:
                NGINX_CONFIG: "./nginx.conf.dev.template"
        ports:
            - "3000:80"
    worker:
        environment:
            - ENV=dev
            - PROCESS_COUNT=6
            - MONGODB_URL=mongodb://mongodb:27017/soarch-db
        volumes:
            - ./backend:/backend
            - ./midi_files:/midi_files
    mongo:
        image: mongo:latest
        container_name: mongodb