version: "3"

services:
    redis:
        image: redis:alpine
        container_name: redis-cache
        expose:
            - "6379"
    backend:
        build: backend
        depends_on:
            - redis
        container_name: midi-search-backend
        image: midi-search-backend
        environment:
            - HYPERCORN_CMD_ARGS=--reload
            - REDIS_URL=redis://redis-cache
            - PORT=8080
        ports:
            - "8080:8080"
    frontend:
        build: frontend
        depends_on:
            - redis
            - backend
        container_name: midi-search-frontend
        image: midi-search-frontend
        environment:
            - API_HOST=http://midi-search-backend:8080
