services:
    redis-queue:
        restart: unless-stopped
    backend:
        restart: unless-stopped
        volumes:
            - /backend
            - /midi_files
        environment:
            - ENV=prod
            - CLOUD_STORAGE_CREDENTIALS=${CLOUD_STORAGE_CREDENTIALS}
            - BUCKET_NAME=${BUCKET_NAME}
        command: hypercorn -b 0.0.0.0:8080 "src/app:create_app()"
    frontend:
        build:
            args:
                NGINX_CONFIG: "./nginx.conf.prod.template"
        restart: unless-stopped
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - "${CERT_PATH}:/cert/fullchain.pem"
            - "${PRIVKEY_PATH}:/cert/privkey.pem"
    worker:
        restart: unless-stopped
        volumes:
            - /backend
            - /midi_files
        environment:
            - ENV=prod
            - PROCESS_COUNT=4
            - CLOUD_STORAGE_CREDENTIALS=${CLOUD_STORAGE_CREDENTIALS}
            - BUCKET_NAME=${BUCKET_NAME}
        command: worker.run_worker:setup_broker worker.tasks --path src/ --processes 2 --threads 1
    parser-cron:
        build: backend
        container_name: midi-search-parser-cron
        image: midi-search-backend
        environment:
            - CLOUD_STORAGE_CREDENTIALS=${CLOUD_STORAGE_CREDENTIALS}
            - BUCKET_NAME=${BUCKET_NAME}
            - MONGODB_URL=mongodb://mongodb:27017/soarch-db
        command: python3 src/run_parser_cron.py
    mongo:
        volumes:
            - /var/lib/mongodb/data:/data/db