services:
    backend:
        environment:
            - ENV=dev
        volumes:
            - ./backend:/backend
            - ./midi_files:/midi_files
    frontend:
        environment:
            - PORT=80
        build:
            args:
                NGINX_CONFIG: "./nginx.conf.dev.template"
        ports:
            - "3000:80"
    worker:
        environment:
            - ENV=dev
            - PROCESS_COUNT=6
        volumes:
            - ./backend:/backend
            - ./midi_files:/midi_files
    mongo:
        volumes:
            - ./mongo_data:/data/db
    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=example
            - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
