services:
    backend:
        image: ${BACKEND_IMAGE}
        volumes:
            - /backend
            - /midi_files
    frontend:
        image: ${FRONTEND_IMAGE}
    worker:
        image: ${WORKER_IMAGE}
        volumes:
            - /backend
            - /midi_files