services:
    redis-queue:
        restart: unless-stopped
    backend:
        restart: unless-stopped
        volumes:
            - /backend
            - /midi_files
        environment:
            - ENV=prod
            - CLOUD_STORAGE_CREDENTIALS=${CLOUD_STORAGE_CREDENTIALS}
            - BUCKET_NAME=${BUCKET_NAME}
    frontend:
        build:
            args:
                NGINX_CONFIG: "./nginx.conf.prod.template"
        restart: unless-stopped
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - "${CERT_PATH}:/cert/fullchain.pem"
            - "${PRIVKEY_PATH}:/cert/privkey.pem"
    worker:
        restart: unless-stopped
        volumes:
            - /backend
            - /midi_files
        environment:
            - ENV=prod
            - PROCESS_COUNT=4
            - CLOUD_STORAGE_CREDENTIALS=${CLOUD_STORAGE_CREDENTIALS}
            - BUCKET_NAME=${BUCKET_NAME}
        command: app.worker.run_worker app.worker.tasks --path src/ --processes 2 --threads 1
    mongo:
        volumes:
            - /var/lib/mongodb/data:/data/db