version: "3"

services:
    redis:
        image: redis:alpine
        container_name: redis-cache
        expose:
            - "6379"
    redis-queue:
        image: redis:alpine
        container_name: redis-queue
        expose:
            - "6379"
    backend:
        build: backend
        depends_on:
            - redis
        container_name: midi-search-backend
        image: midi-search-backend
        environment:
            - CLOUD_STORAGE_CREDENTIALS=${CLOUD_STORAGE_CREDENTIALS}
            - BUCKET_NAME=${BUCKET_NAME}
            - HYPERCORN_CMD_ARGS=--reload
            - REDIS_CACHE_URL=redis://redis-cache
            - REDIS_QUEUE_URL=redis://redis-queue
            - PORT=8080
        ports:
            - "8080:8080"
    frontend:
        build: frontend
        depends_on:
            - redis
            - backend
        container_name: midi-search-frontend
        image: midi-search-frontend
        environment:
            - API_HOST=http://midi-search-backend:8080
    worker:
        build: backend
        environment:
            - CLOUD_STORAGE_CREDENTIALS=${CLOUD_STORAGE_CREDENTIALS}
            - BUCKET_NAME=${BUCKET_NAME}
            - REDIS_CACHE_URL=redis://redis-cache
            - REDIS_QUEUE_URL=redis://redis-queue
        depends_on:
            - redis
        container_name: midi-search-worker
        image: midi-search-worker
        entrypoint: dramatiq
        command: app.worker.run_worker app.worker.tasks --path src/ --processes 1 --threads 1 --watch .