services:
    redis:
        restart: unless-stopped
    backend:
        restart: unless-stopped
        volumes:
            - /backend
            - /midi_files
        environment:
            - ENV=prod
    frontend:
        build:
            args:
                NGINX_CONFIG: "./nginx.conf.prod.template"
        restart: unless-stopped
        environment:
            - PORT=443
            - PROTOCOL=ssl
        ports:
            - "443:443"
        volumes:
            - "${CERT_PATH}:/cert/fullchain.pem"
            - "${PRIVKEY_PATH}:/cert/privkey.pem"
    worker:
        restart: unless-stopped
        volumes:
            - /backend
            - /midi_files
        environment:
            - ENV=prod