version: "3"

services:
    redis-queue:
        image: redis:alpine
        container_name: redis-queue
        expose:
            - "6379"
    backend:
        build: backend
        container_name: midi-search-backend
        image: midi-search-backend
        environment:
            - HYPERCORN_CMD_ARGS=--reload
            - REDIS_QUEUE_URL=redis://redis-queue
            - PORT=8080
            - MONGODB_URL=mongodb://mongodb:27017/soarch-db
            - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
            - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
        ports:
            - "8080:8080"
        command: hypercorn --reload -b 0.0.0.0:8080 "src/app:create_app()"
    frontend:
        build: frontend
        depends_on:
            - backend
        container_name: midi-search-frontend
        image: midi-search-frontend
        environment:
            - API_HOST=http://midi-search-backend:8080
    worker:
        build: backend
        environment:
            - REDIS_QUEUE_URL=redis://redis-queue
            - MONGODB_URL=mongodb://mongodb:27017/soarch-db
            - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
            - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
        container_name: midi-search-worker
        image: midi-search-worker
        entrypoint: dramatiq
        command: worker.run_worker:setup_broker worker.tasks --path src/ --processes 1 --threads 1 --watch .
    mongo:
        image: mongo:latest
        container_name: mongodb