version: "3"

services:
    redis:
        image: redis:alpine
        container_name: redis-cache
        expose:
            - "6379"
    backend:
        build: backend
        container_name: midi-search-backend
        image: midi-search-backend
        volumes:
            - ./backend:/backend
        environment:
            - HYPERCORN_CMD_ARGS=--reload
            - PORT=8080
            - REDIS_URL=redis://redis-cache
            - ENV=dev
        ports:
            - "8080:8080"
    frontend:
        build: frontend
        container_name: midi-search-frontend
        image: midi-search-frontend
        environment:
            - API_HOST=http://midi-search-backend:8080
            - PORT=80
        ports:
            - "3000:80"
